language: node_js
node_js:
- '10.5'
script:
- npm run build
- npm run test:unit
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GH_TOKEN"
  keep-history: true
  local-dir: dist
  on:
    branch: master
webhooks:
  email: false
  urls:
  - https://webhooks.gitter.im/e/1af305337aa41e422c46
  on_success: always
  on_failure: always
  on_start: false
env:
  global:
    secure: WjZ8+fcMpzIKF3YoCXnXgjmJI47bS05s7DHEyxStQ6hLU7wInsCB+KPuhL7ngiykALH1b0u1ooxyego59ZJbSgd/+ywIn4y/JaF9h0R0nqs9ij0BOfjva1W5sUmSEjepEX1NvNUiD86MloKKH69KJ7q6aoaqNKSFwsRaCOhJB3bf5+cbN6Zte+bplATF8oRRYi68+5t84Moq4cVf6KiDU04OUDuyTGkNJB7V0BapVpa/b+wVdTKdCtXo5RQqGehvV2z9PsUXlVesERPzqM+//H0XmVgUA6APnVjvieJQF4oW3n2vWrm46/ZKuEM+QH66+3W7WZIxXvwq0kBup1phex3PpZu5iyIQjDjxjuA9QAKhzbUSxQnOYb0GkD+yIMbCj3JwnJZjjiCG25cRb3jmrf7Gf8HAY2F2Porcn+avmmSFzOiVEjFJNIqM354kd/2Ca2K+/SiWByj4e/zYCcnWGQn2hoJPGeWh3w2TaUrFgB5dlO5dPpAPp4rjPb0NlMNlQm4ZlnufWemccBQIruoLpSZbW8zKC75pU9pQT9mq9aMXcoAnq+vJQb3DObLG8xuJCqJYZxCQdbFPsKkwJd+pwdUoKTUt0qnuu3MC8T/JuNWxUHIGQlsS7f/XdnOdrNWlT5nkYqv11YfFUFO68LNvkvlSn0V0bI4fN1mRjSztiKE=
